title: <p align="center"> Rachdyan Naufal </p>

logo: "/images/foto.png?raw=true"

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/rachdyan/">LinkedIn</a> |
  <a href="https://www.upwork.com/freelancers/rachdyannaufal">Upwork</a> |
  <a href="https://github.com/rachdyan">GitHub</a>
  </p>
  
  <p align="justify">
  Currently working as an ESG Data Analyst at Datacie. I have experience working with diverse data and tools, from financial market disclosures to ESG and geospatial data. My approach to every new challenge is the same: I focus on deeply understanding the domain knowledge first. This ensures that the solutions I build are not just technically correct, but are genuinely practical and useful for the subject at hand.

  <br><br>

  As a hands-on generalist, I primarily use Python and R to create these solutions but can quickly adapt to other tools to get the job done. I enjoy the full process of automating data collection, cleaning up messy information, and building interactive dashboards that make the data easy to explore. My focus is always on turning complex, raw information into something clear and actionable.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
