title: <p align="center"> Rachdyan Naufal </p>

logo: "/images/foto.png?raw=true"

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/rachdyan/">LinkedIn</a> |
  <a href="https://www.upwork.com/freelancers/rachdyannaufal">Upwork</a> |
  <a href="https://github.com/rachdyan">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing MS degree in Business Analytics at Simon Business School, University of Rochester.
  <br><br>
  I am currently a Machine Learning Research Intern at Skim AI Technologies with a focus on NLP and Deep Learning research.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
